/*
 screenfull
 v5.0.0 - 2019-09-09
 (c) Sindre Sorhus; MIT License
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
(function(){var a="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},d="undefined"!==typeof module&&module.exports,c=function(){for(var c,b=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),
"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],d=0,e=b.length,k={};d<e;d++)if((c=b[d])&&c[1]in a){for(d=0;d<c.length;d++)k[b[0][d]]=c[d];return k}return!1}(),e={change:c.fullscreenchange,error:c.fullscreenerror},b={request:function(b){return new Promise(function(d,e){var f=function(){this.off("change",
f);d()}.bind(this);this.on("change",f);b=b||a.documentElement;Promise.resolve(b[c.requestFullscreen]())["catch"](e)}.bind(this))},exit:function(){return new Promise(function(b,d){if(this.isFullscreen){var e=function(){this.off("change",e);b()}.bind(this);this.on("change",e);Promise.resolve(a[c.exitFullscreen]())["catch"](d)}else b()}.bind(this))},toggle:function(a){return this.isFullscreen?this.exit():this.request(a)},onchange:function(a){this.on("change",a)},onerror:function(a){this.on("error",a)},
on:function(b,c){var d=e[b];d&&a.addEventListener(d,c,!1)},off:function(b,c){var d=e[b];d&&a.removeEventListener(d,c,!1)},raw:c};c?(Object.defineProperties(b,{isFullscreen:{get:function(){return!!a[c.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[c.fullscreenElement]}},isEnabled:{enumerable:!0,get:function(){return!!a[c.fullscreenEnabled]}}}),d?module.exports=b:window.screenfull=b):d?module.exports={isEnabled:!1}:window.screenfull={isEnabled:!1}})();
function buildIOSMeta(){for(var a=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],d=0;d<a.length;d++){var c=document.createElement("meta");c.name=a[d].name;c.content=a[d].content;var e=window.document.head.querySelector('meta[name="'+c.name+'"]');e&&e.parentNode.removeChild(e);window.document.head.appendChild(c)}}
function hideIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","none");jQuery(".xxx-ios-fullscreen-scroll").css("display","none");jQuery(".xxx-game-iframe-full").removeClass("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){jQuery("body").append('<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","block");jQuery(".xxx-ios-fullscreen-scroll").css("display","block")}
function __iosResize(){window.scrollTo(0,0);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&jQuery(".xxx-game-iframe-full").addClass("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;
case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}function iosInIframe(){try{return window.self!==window.top}catch(a){return!0}}$(document).ready(function(){platform&&"iPhone"===platform.product&&!iosInIframe()&&(buildIOSFullscreenPanel(),buildIOSMeta())});
jQuery(window).resize(function(){platform&&"iPhone"===platform.product&&!iosInIframe()&&iosResize()});
(function(){function a(a){a=String(a);return a.charAt(0).toUpperCase()+a.slice(1)}function d(a,b){var c=-1,d=a?a.length:0;if("number"==typeof d&&-1<d&&d<=u)for(;++c<d;)b(a[c],c,a);else e(a,b)}function c(b){b=String(b).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(b)?b:a(b)}function e(a,b){for(var c in a)z.call(a,c)&&b(a[c],c,a)}function b(b){return null==b?a(b):B.call(b).slice(8,-1)}function g(a,b){var c=null!=a?typeof a[b]:"number";return!/^(?:boolean|number|string|undefined)$/.test(c)&&
("object"==c?!!a[b]:!0)}function f(a){return String(a).replace(/([ -])(?!$)/g,"$1?")}function n(a,b){var c=null;d(a,function(d,e){c=b(c,d,e,a)});return c}function q(a){function d(b){return n(b,function(b,d){var e=d.pattern||f(d);!b&&(b=RegExp("\\b"+e+" *\\d+[.\\w_]*","i").exec(a)||RegExp("\\b"+e+" *\\w+-[\\w]*","i").exec(a)||RegExp("\\b"+e+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(a))&&((b=String(d.label&&!RegExp(e,"i").test(d.label)?d.label:b).split("/"))[1]&&!/[\d.]+/.test(b[0])&&(b[0]+=
" "+b[1]),d=d.label||d,b=c(b[0].replace(RegExp(e,"i"),d).replace(RegExp("; *(?:"+d+"[_-])?","i")," ").replace(RegExp("("+d+")[-_.]?(\\w)","i"),"$1 $2")));return b})}function k(b){return n(b,function(b,c){return b||(RegExp(c+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(a)||0)[1]||null})}var l=p,m=a&&"object"==typeof a&&"String"!=b(a);m&&(l=a,a=null);var H=l.navigator||{},v=H.userAgent||"";a||(a=v);var x=m?!!H.likeChrome:/\bChrome\b/.test(a)&&!/internal|\n/i.test(B.toString()),
u=m?"Object":"ScriptBridgingProxyObject",z=m?"Object":"Environment",E=m&&l.java?"JavaPackage":b(l.java),R=m?"Object":"RuntimeObject";z=(E=/\bJava/.test(E)&&l.java)&&b(l.environment)==z;var S=E?"a":"\u03b1",T=E?"b":"\u03b2",O=l.document||{},J=l.operamini||l.opera,L=w.test(L=m&&J?J["[[Class]]"]:b(J))?L:J=null,h,M=a;m=[];var N=null,K=a==v;v=K&&J&&"function"==typeof J.version&&J.version();var C=function(b){return n(b,function(b,c){return b||RegExp("\\b"+(c.pattern||f(c))+"\\b","i").exec(a)&&(c.label||
c)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),r=function(b){return n(b,function(b,c){return b||RegExp("\\b"+(c.pattern||f(c))+"\\b","i").exec(a)&&(c.label||c)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),D=d([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),I=function(b){return n(b,function(b,c,d){return b||(c[D]||c[/^[a-z]+(?: +[a-z]+\b)*/i.exec(D)]||RegExp("\\b"+f(d)+"(?:\\b|\\w*\\d)","i").exec(a))&&d})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),t=function(b){return n(b,function(b,d){var e=d.pattern||f(d);if(!b&&(b=RegExp("\\b"+e+"(?:/[\\d.]+|[ \\w.]*)","i").exec(a))){var g=b,l=d.label||d,h={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};e&&l&&/^Win/i.test(g)&&!/^Windows Phone /i.test(g)&&(h=h[/[\d.]+$/.exec(g)])&&(g="Windows "+h);g=String(g);e&&l&&(g=g.replace(RegExp(e,"i"),l));b=g=c(g.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,"$1").replace(/\/(\d)/,
" $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return b})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X","Macintosh","Mac",
"Windows 98;","Windows "]);C&&(C=[C]);I&&!D&&(D=d([I]));if(h=/\bGoogle TV\b/.exec(D))D=h[0];/\bSimulator\b/i.test(a)&&(D=(D?D+" ":"")+"Simulator");"Opera Mini"==r&&/\bOPiOS\b/.test(a)&&m.push("running in Turbo/Uncompressed mode");"IE"==r&&/\blike iPhone OS\b/.test(a)?(h=q(a.replace(/like iPhone OS/,"")),I=h.manufacturer,D=h.product):/^iP/.test(D)?(r||(r="Safari"),t="iOS"+((h=/ OS ([\d_]+)/i.exec(a))?" "+h[1].replace(/_/g,"."):"")):"Konqueror"!=r||/buntu/i.test(t)?I&&"Google"!=I&&(/Chrome/.test(r)&&
!/\bMobile Safari\b/i.test(a)||/\bVita\b/.test(D))||/\bAndroid\b/.test(t)&&/^Chrome/.test(r)&&/\bVersion\//i.test(a)?(r="Android Browser",t=/\bAndroid\b/.test(t)?t:"Android"):"Silk"==r?(/\bMobi/i.test(a)||(t="Android",m.unshift("desktop mode")),/Accelerated *= *true/i.test(a)&&m.unshift("accelerated")):"PaleMoon"==r&&(h=/\bFirefox\/([\d.]+)\b/.exec(a))?m.push("identifying as Firefox "+h[1]):"Firefox"==r&&(h=/\b(Mobile|Tablet|TV)\b/i.exec(a))?(t||(t="Firefox OS"),D||(D=h[1])):!r||(h=!/\bMinefield\b/i.test(a)&&
/\b(?:Firefox|Safari)\b/.exec(r))?(r&&!D&&/[\/,]|^[^(]+?\)/.test(a.slice(a.indexOf(h+"/")+8))&&(r=null),(h=D||I||t)&&(D||I||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(t))&&(r=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(t)?t:h)+" Browser")):"Electron"==r&&(h=(/\bChrome\/([\d.]+)\b/.exec(a)||0)[1])&&m.push("Chromium "+h):t="Kubuntu";v||(v=k(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",f(r),"(?:Firefox|Minefield|NetFront)"]));
if(h="iCab"==C&&3<parseFloat(v)&&"WebKit"||/\bOpera\b/.test(r)&&(/\bOPR\b/.test(a)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(a)&&!/^(?:Trident|EdgeHTML)$/.test(C)&&"WebKit"||!C&&/\bMSIE\b/i.test(a)&&("Mac OS"==t?"Tasman":"Trident")||"WebKit"==C&&/\bPlayStation\b(?! Vita\b)/i.test(r)&&"NetFront")C=[h];"IE"==r&&(h=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(a)||0)[1])?(r+=" Mobile",t="Windows Phone "+(/\+$/.test(h)?h:h+".x"),m.unshift("desktop mode")):/\bWPDesktop\b/i.test(a)?(r="IE Mobile",t="Windows Phone 8.x",
m.unshift("desktop mode"),v||(v=(/\brv:([\d.]+)/.exec(a)||0)[1])):"IE"!=r&&"Trident"==C&&(h=/\brv:([\d.]+)/.exec(a))&&(r&&m.push("identifying as "+r+(v?" "+v:"")),r="IE",v=h[1]);if(K){if(g(l,"global"))if(E&&(h=E.lang.System,M=h.getProperty("os.arch"),t=t||h.getProperty("os.name")+" "+h.getProperty("os.version")),z){try{v=l.require("ringo/engine").version.join("."),r="RingoJS"}catch(Q){(h=l.system)&&h.global.system==l.system&&(r="Narwhal",t||(t=h[0].os||null))}r||(r="Rhino")}else"object"==typeof l.process&&
!l.process.browser&&(h=l.process)&&("object"==typeof h.versions&&("string"==typeof h.versions.electron?(m.push("Node "+h.versions.node),r="Electron",v=h.versions.electron):"string"==typeof h.versions.nw&&(m.push("Chromium "+v,"Node "+h.versions.node),r="NW.js",v=h.versions.nw)),r||(r="Node.js",M=h.arch,t=h.platform,v=(v=/[\d.]+/.exec(h.version))?v[0]:null));else b(h=l.runtime)==u?(r="Adobe AIR",t=h.flash.system.Capabilities.os):b(h=l.phantom)==R?(r="PhantomJS",v=(h=h.version||null)&&h.major+"."+h.minor+
"."+h.patch):"number"==typeof O.documentMode&&(h=/\bTrident\/(\d+)/i.exec(a))?(v=[v,O.documentMode],(h=+h[1]+4)!=v[1]&&(m.push("IE "+v[1]+" mode"),C&&(C[1]=""),v[1]=h),v="IE"==r?String(v[1].toFixed(1)):v[0]):"number"==typeof O.documentMode&&/^(?:Chrome|Firefox)\b/.test(r)&&(m.push("masking as "+r+" "+v),r="IE",v="11.0",C=["Trident"],t="Windows");t=t&&c(t)}v&&(h=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(v)||/(?:alpha|beta)(?: ?\d)?/i.exec(a+";"+(K&&H.appMinorVersion))||/\bMinefield\b/i.test(a)&&
"a")&&(N=/b/i.test(h)?"beta":"alpha",v=v.replace(RegExp(h+"\\+?$"),"")+("beta"==N?T:S)+(/\d+\+?/.exec(h)||""));if("Fennec"==r||"Firefox"==r&&/\b(?:Android|Firefox OS)\b/.test(t))r="Firefox Mobile";else if("Maxthon"==r&&v)v=v.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(D))"Xbox 360"==D&&(t=null),"Xbox 360"==D&&/\bIEMobile\b/.test(a)&&m.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(r)&&(!r||D||/Browser|Mobi/.test(r))||"Windows CE"!=t&&!/Mobi/i.test(a))if("IE"==r&&K)try{null===l.external&&
m.unshift("platform preview")}catch(Q){m.unshift("embedded")}else(/\bBlackBerry\b/.test(D)||/\bBB10\b/.test(a))&&(h=(RegExp(D.replace(/ +/g," *")+"/([.\\d]+)","i").exec(a)||0)[1]||v)?(h=[h,/BB10/.test(a)],t=(h[1]?(D=null,I="BlackBerry"):"Device Software")+" "+h[0],v=null):this!=e&&"Wii"!=D&&(K&&J||/Opera/.test(r)&&/\b(?:MSIE|Firefox)\b/i.test(a)||"Firefox"==r&&/\bOS X (?:\d+\.){2,}/.test(t)||"IE"==r&&(t&&!/^Win/.test(t)&&5.5<v||/\bWindows XP\b/.test(t)&&8<v||8==v&&!/\bTrident\b/.test(a)))&&!w.test(h=
q.call(e,a.replace(w,"")+";"))&&h.name&&(h="ing as "+h.name+((h=h.version)?" "+h:""),w.test(r)?(/\bIE\b/.test(h)&&"Mac OS"==t&&(t=null),h="identify"+h):(h="mask"+h,r=L?c(L.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(h)&&(t=null),K||(v=null)),C=["Presto"],m.push(h));else r+=" Mobile";if(h=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(a)||0)[1]){h=[parseFloat(h.replace(/\.(\d)$/,".0$1")),h];if("Safari"==r&&"+"==h[1].slice(-1))r="WebKit Nightly",N="alpha",v=h[1].slice(0,-1);else if(v==h[1]||v==(h[2]=
(/\bSafari\/([\d.]+\+?)/i.exec(a)||0)[1]))v=null;h[1]=(/\bChrome\/([\d.]+)/i.exec(a)||0)[1];537.36==h[0]&&537.36==h[2]&&28<=parseFloat(h[1])&&"WebKit"==C&&(C=["Blink"]);K&&(x||h[1])?(C&&(C[1]="like Chrome"),h=h[1]||(h=h[0],530>h?1:532>h?2:532.05>h?3:533>h?4:534.03>h?5:534.07>h?6:534.1>h?7:534.13>h?8:534.16>h?9:534.24>h?10:534.3>h?11:535.01>h?12:535.02>h?"13+":535.07>h?15:535.11>h?16:535.19>h?17:536.05>h?18:536.1>h?19:537.01>h?20:537.11>h?"21+":537.13>h?23:537.18>h?24:537.24>h?25:537.36>h?26:"Blink"!=
C?"27":"28")):(C&&(C[1]="like Safari"),h=(h=h[0],400>h?1:500>h?2:526>h?3:533>h?4:534>h?"4+":535>h?5:537>h?6:538>h?7:601>h?8:"8"));C&&(C[1]+=" "+(h+="number"==typeof h?".x":/[.+]/.test(h)?"":"+"));"Safari"==r&&(!v||45<parseInt(v))&&(v=h)}"Opera"==r&&(h=/\bzbov|zvav$/.exec(t))?(r+=" ",m.unshift("desktop mode"),"zvav"==h?(r+="Mini",v=null):r+="Mobile",t=t.replace(RegExp(" *"+h+"$"),"")):"Safari"==r&&/\bChrome\b/.exec(C&&C[1])&&(m.unshift("desktop mode"),r="Chrome Mobile",v=null,/\bOS X\b/.test(t)?(I=
"Apple",t="iOS 4.3+"):t=null);v&&0==v.indexOf(h=/[\d.]+$/.exec(t))&&-1<a.indexOf("/"+h+"-")&&(t=String(t.replace(h,"")).replace(/^ +| +$/g,""));C&&!/\b(?:Avant|Nook)\b/.test(r)&&(/Browser|Lunascape|Maxthon/.test(r)||"Safari"!=r&&/^iOS/.test(t)&&/\bSafari\b/.test(C[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(r)&&C[1])&&(h=C[C.length-1])&&m.push(h);m.length&&(m=["("+m.join("; ")+")"]);I&&D&&0>D.indexOf(I)&&m.push("on "+I);D&&m.push((/^on /.test(m[m.length-
1])?"":"on ")+D);if(t){var P=(h=/ ([\d.+]+)$/.exec(t))&&"/"==t.charAt(t.length-h[0].length-1);t={architecture:32,family:h&&!P?t.replace(h[0],""):t,version:h?h[1]:null,toString:function(){var a=this.version;return this.family+(a&&!P?" "+a:"")+(64==this.architecture?" 64-bit":"")}}}(h=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(M))&&!/\bi686\b/i.test(M)?(t&&(t.architecture=64,t.family=t.family.replace(RegExp(" *"+h),"")),r&&(/\bWOW64\b/i.test(a)||K&&/\w(?:86|32)$/.test(H.cpuClass||H.platform)&&!/\bWin64; x64\b/i.test(a))&&
m.unshift("32-bit")):t&&/^OS X/.test(t.family)&&"Chrome"==r&&39<=parseFloat(v)&&(t.architecture=64);a||(a=null);l={};l.description=a;l.layout=C&&C[0];l.manufacturer=I;l.name=r;l.prerelease=N;l.product=D;l.ua=a;l.version=r&&v;l.os=t||{architecture:null,family:null,version:null,toString:function(){return"null"}};l.parse=q;l.toString=function(){return this.description||""};l.version&&m.unshift(v);l.name&&m.unshift(r);t&&r&&(t!=String(t).split(" ")[0]||t!=r.split(" ")[0]&&!D)&&m.push(D?"("+t+")":"on "+
t);m.length&&(l.description=m.join(" "));return l}var k={"function":!0,object:!0},p=k[typeof window]&&window||this,l=k[typeof exports]&&exports;k=k[typeof module]&&module&&!module.nodeType&&module;var m=l&&k&&"object"==typeof global&&global;!m||m.global!==m&&m.window!==m&&m.self!==m||(p=m);var u=Math.pow(2,53)-1,w=/\bOpera/;m=Object.prototype;var z=m.hasOwnProperty,B=m.toString,x=q();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(p.platform=x,define(function(){return x})):l&&
k?e(x,function(a,b){l[b]=a}):p.platform=x}).call(this);var s_iScaleFactor=1,s_bIsIphone=!1,s_iOffsetX,s_iOffsetY;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");for(-1!==navigator.userAgent.toLowerCase().indexOf("iphone")&&(s_bIsIphone=!0);a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}
window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function getSize(a){var d=a.toLowerCase(),c=window.document,e=c.documentElement;if(void 0===window["inner"+a])a=e["client"+a];else if(window["inner"+a]!=e["client"+a]){var b=c.createElement("body");b.id="vpw-test-b";b.style.cssText="overflow:scroll";var g=c.createElement("div");g.id="vpw-test-d";g.style.cssText="position:absolute;top:-1000px";g.innerHTML="<style>@media("+d+":"+e["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";b.appendChild(g);e.insertBefore(b,c.head);
a=7==g["offset"+a]?e["client"+a]:window["inner"+a];e.removeChild(b)}else a=window["inner"+a];return a}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a="safari"===platform.name.toLowerCase()?getIOSWindowHeight():getSize("Height");var d=getSize("Width");_checkOrientation(d,a);s_iScaleFactor=Math.min(a/CANVAS_HEIGHT,d/CANVAS_WIDTH);var c=Math.round(CANVAS_WIDTH*s_iScaleFactor),e=Math.round(CANVAS_HEIGHT*s_iScaleFactor);if(e<a){var b=a-e;e+=b;c+=CANVAS_WIDTH/CANVAS_HEIGHT*b}else c<d&&(b=d-c,c+=b,e+=CANVAS_HEIGHT/CANVAS_WIDTH*b);b=a/2-e/2;var g=d/2-c/2,f=CANVAS_WIDTH/c;if(g*f<-EDGEBOARD_X||
b*f<-EDGEBOARD_Y)s_iScaleFactor=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),d/(CANVAS_WIDTH-2*EDGEBOARD_X)),c=Math.round(CANVAS_WIDTH*s_iScaleFactor),e=Math.round(CANVAS_HEIGHT*s_iScaleFactor),b=(a-e)/2,g=(d-c)/2,f=CANVAS_WIDTH/c;s_iOffsetX=-1*g*f;s_iOffsetY=-1*b*f;0<=b&&(s_iOffsetY=0);0<=g&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=
2*c,s_oStage.canvas.height=2*e,canvas.style.width=c+"px",canvas.style.height=e+"px",s_oStage.scaleX=s_oStage.scaleY=2*Math.min(c/CANVAS_WIDTH,e/CANVAS_HEIGHT)):s_bMobile||isChrome()?($("#canvas").css("width",c+"px"),$("#canvas").css("height",e+"px")):(s_oStage.canvas.width=c,s_oStage.canvas.height=e,s_iScaleFactor=Math.min(c/CANVAS_WIDTH,e/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>b||(b=(a-e)/2);$("#canvas").css("top",b+"px");$("#canvas").css("left",g+"px");fullscreenHandler()}}
function _checkOrientation(a,d){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>d?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function createBitmap(a,d,c){var e=new createjs.Bitmap(a),b=new createjs.Shape;d&&c?b.graphics.beginFill("#fff").drawRect(-d/2,-c/2,d,c):b.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);e.hitArea=b;return e}function createSprite(a,d,c,e,b,g){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-c,-e,b,g);a.hitArea=d;return a}
function randomFloatBetween(a,d,c){"undefined"===typeof c&&(c=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(c))}function shuffle(a){for(var d=a.length,c,e;0!==d;)e=Math.floor(Math.random()*d),--d,c=a[d],a[d]=a[e],a[e]=c;return a}function formatTime(a){a/=1E3;var d=Math.floor(a/60);a=parseFloat(a-60*d).toFixed(1);var c="";c=10>d?c+("0"+d+":"):c+(d+":");return 10>a?c+("0"+a):c+a}function degreesToRadians(a){return a*Math.PI/180}
function checkRectCollision(a,d){var c=getBounds(a,.9);var e=getBounds(d,.98);return calculateIntersection(c,e)}function calculateIntersection(a,d){var c,e,b,g;var f=a.x+(c=a.width/2);var n=a.y+(e=a.height/2);var q=d.x+(b=d.width/2);var k=d.y+(g=d.height/2);f=Math.abs(f-q)-(c+b);n=Math.abs(n-k)-(e+g);return 0>f&&0>n?(f=Math.min(Math.min(a.width,d.width),-f),n=Math.min(Math.min(a.height,d.height),-n),{x:Math.max(a.x,d.x),y:Math.max(a.y,d.y),width:f,height:n,rect1:a,rect2:d}):null}
function getBounds(a,d){var c={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){c.x2=-Infinity;c.y2=-Infinity;var e=a.children,b=e.length,g;for(g=0;g<b;g++){var f=getBounds(e[g],1);f.x<c.x&&(c.x=f.x);f.y<c.y&&(c.y=f.y);f.x+f.width>c.x2&&(c.x2=f.x+f.width);f.y+f.height>c.y2&&(c.y2=f.y+f.height)}Infinity==c.x&&(c.x=0);Infinity==c.y&&(c.y=0);Infinity==c.x2&&(c.x2=0);Infinity==c.y2&&(c.y2=0);c.width=c.x2-c.x;c.height=c.y2-c.y;delete c.x2;delete c.y2}else{if(a instanceof createjs.Bitmap){b=
a.sourceRect||a.image;g=b.width*d;var n=b.height*d}else if(a instanceof createjs.Sprite)if(a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image){b=a.spriteSheet.getFrame(a.currentFrame);g=b.rect.width;n=b.rect.height;e=b.regX;var q=b.regY}else c.x=a.x||0,c.y=a.y||0;else c.x=a.x||0,c.y=a.y||0;e=e||0;g=g||0;q=q||0;n=n||0;c.regX=e;c.regY=q;b=a.localToGlobal(0-e,0-q);f=a.localToGlobal(g-e,n-q);g=a.localToGlobal(g-e,0-q);e=a.localToGlobal(0-e,n-q);c.x=
Math.min(Math.min(Math.min(b.x,f.x),g.x),e.x);c.y=Math.min(Math.min(Math.min(b.y,f.y),g.y),e.y);c.width=Math.max(Math.max(Math.max(b.x,f.x),g.x),e.x)-c.x;c.height=Math.max(Math.max(Math.max(b.y,f.y),g.y),e.y)-c.y}return c}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};
(function(){function a(a){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in c?document.body.className=c[a.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",a):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(d="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(d="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function playSound(a,d,c){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(d),s_aSounds[a].loop(c),s_aSounds[a]):null}
function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(d)}function setMute(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(d)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var d=window.location.search.substring(1).split("&"),c=0;c<d.length;c++){var e=d[c].split("=");if(e[0]==a)return e[1]}}function distanceV2(a,d){var c=a.x-d.x,e=a.y-d.y;return Math.sqrt(c*c+e*e)}function randomRange(a,d){return Math.floor(Math.random()*(d-a))+a}function saveItem(a,d){localStorage.setItem(a,d)}function getItem(a){return localStorage.getItem(a)}function clearAllItem(){localStorage.clear()}
function centerBetweenPointsV2(a,d){var c=new CVector2;c.set(.5*(a.getX()+d.getX()),.5*(a.getY()+d.getY()));return c}function perpProductV2(a,d){return a.getX()*d.getY()-a.getY()*d.getX()}function dotProductV2(a,d){return a.getX()*d.getX()+a.getY()*d.getY()}
function inSegment(a,d){if(d.getPointA().x!=d.getPointB().getX()){if(d.getPointA().getX()<=a.getX()&&a.getX()<=d.getPointB().getX()||d.getPointA().getX()>=a.getX()&&a.getX()>=d.getPointB().getX())return 1}else if(d.getPointA().getY()<=a.getY()&&a.getY()<=d.getPointB().getY()||d.getPointA().getY()>=a.getY()&&a.getY()>=d.getPointB().getY())return 1;return 0}
function intersect2D_Segments(a,d,c,e){var b=new CVector2,g=new CVector2,f=new CVector2;b.set(a.getPointB().getX()-a.getPointA().getX(),a.getPointB().getY()-a.getPointA().getY());g.set(d.getPointB().getX()-d.getPointA().getX(),d.getPointB().getY()-d.getPointA().getY());f.set(a.getPointA().getX()-d.getPointA().getX(),a.getPointA().getY()-d.getPointA().getY());var n=perpProductV2(b,g);if(1E-8>Math.abs(n)){b=dotProductV2(b,b);n=dotProductV2(g,g);if(0==b&&0==n){if(a.getPointA().getX()!=d.getPointA().getX()||
a.getPointA().getY()!=d.getPointA().getY())return 0;a.getPointA();return 1}if(0==b){if(0==inSegment(a.getPointA(),d))return 0;a.getPointA();return 1}if(0==n){if(0==inSegment(d.getPointA(),a))return 0;d.getPointA();return 1}b=new CVector2;b.set(a.getPointB().getX()-d.getPointA().getX(),a.getPointB().getY()-d.getPointA().getY());0!=g.getX()?(a=f.getX()/g.getX(),f=b.getX()/g.getX()):(a=f.getY()/g.getY(),f=b.getY()/g.getY());a>f&&(b=a,a=f,f=b);if(1<a||0>f)return 0;a=0>a?0:a;f=1<f?1:f;if(a==f)return c.set(d.getPointA().getX()+
a*g.getX(),d.getPointA().getY()+a*g.getY()),1;c.set(d.getPointA().getX()+a*g.getX(),d.getPointA().getY()+a*g.getY());e.set(d.getPointA().getX()+f*g.getX(),d.getPointA().getY()+f*g.getY());return 2}d=perpProductV2(g,f)/n;if(0>d||1<d)return 0;e=perpProductV2(b,f)/n;if(0>e||1<e)return 0;c.set(a.getPointA().getX()+d*b.getX(),a.getPointA().getY()+d*b.getY());return 1}
function getRandomColor(){return"rgba("+(Math.floor(127*Math.random()+255)-127)+","+(Math.floor(127*Math.random()+255)-127)+","+(Math.floor(127*Math.random()+255)-127)+",1)"}function colorLuminance(a,d){a=String(a).replace(/[^0-9a-f]/gi,"");6>a.length&&(a=a[0]+a[0]+a[1]+a[1]+a[2]+a[2]);d=d||0;var c="#",e;for(e=0;3>e;e++){var b=parseInt(a.substr(2*e,2),16);b=Math.round(Math.min(Math.max(0,b+b*d),255)).toString(16);c+=("00"+b).substr(b.length)}return c}function linearLerp(a,d,c){return(1-c)*a+c*d}
function colorLerpShape(a,d,c,e,b,g,f,n,q,k){var p={},l=createjs.Tween.get(d,{override:!0}).wait(e).to({lerp:c.lerp},b,f).call(function(){null!==k&&k();createjs.Tween.removeTweens(l)}).addEventListener("change",function(){var a=parseInt(linearLerp(d.r,c.r,d.lerp)),b=parseInt(linearLerp(d.g,c.g,d.lerp)),e=parseInt(linearLerp(d.b,c.b,d.lerp));p[q]="rgba("+a+","+b+","+e+",1)";g(n,p)})}
function hexToRgb(a){return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?{r:parseInt(a[1],16),g:parseInt(a[2],16),b:parseInt(a[3],16)}:null}
function BoundingBoxEdge(a){for(var d=a[0].getPointA().getX(),c=a[0].getPointA().getY(),e=a[0].getPointA().getX(),b=a[0].getPointA().getY(),g=1;g<a.length;g++)a[g].getPointA().getX()<d?d=a[g].getPointA().getX():a[g].getPointA().getX()>e&&(e=a[g].getPointA().getX()),a[g].getPointA().getY()<c?c=a[g].getPointA().getY():a[g].getPointA().getY()>b&&(b=a[g].getPointA().getY());return{xMin:d,yMin:c,xMax:e,yMax:b}}
function BoundingBox(a){for(var d=a[0].x,c=a[0].y,e=a[0].x,b=a[0].y,g=1;g<a.length;g++)a[g].x<d?d=a[g].x:a[g].x>e&&(e=a[g].x),a[g].y<c?c=a[g].y:a[g].y>b&&(b=a[g].y);return{xMin:d,yMin:c,xMax:e,yMax:b}}function fullscreenHandler(){ENABLE_FULLSCREEN&&!1!==screenfull.isEnabled&&(s_bFullscreen=screenfull.isFullscreen,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut())}
if(screenfull.isEnabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a={},d,c,e,b,g,f;this.init=function(a,q,k){d={};e=c=0;b=a;g=q;f=k};this.addSprite=function(b,e){if(!a.hasOwnProperty(b)){var f=new Image;a[b]=d[b]={szPath:e,oSprite:f,bLoaded:!1};c++}};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){c=0;g.call(f)};this._onSpriteLoaded=function(){b.call(f);++e===c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var a in d)d[a].oSprite.oSpriteLibrary=this,d[a].oSprite.szKey=
a,d[a].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},d[a].oSprite.onerror=function(a){var b=a.currentTarget;setTimeout(function(){d[b.szKey].oSprite.src=d[b.szKey].szPath},500)},d[a].oSprite.src=d[a].szPath};this.setLoaded=function(b){a[b].bLoaded=!0};this.isLoaded=function(b){return a[b].bLoaded};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=840,CANVAS_HEIGHT=1360,CANVAS_WIDTH_HALF=.5*CANVAS_WIDTH,CANVAS_HEIGHT_HALF=.5*CANVAS_HEIGHT,EDGEBOARD_X=72,EDGEBOARD_Y=170,CONFIRMATION_EXIT=0,CONFIRMATION_RESET=1,DISABLE_SOUND_MOBILE=!1,FONT_GAME="Odin-Bold",TEXT_COLOR="#fff",TEXT_COLOR_STROKE="#555555",TEXT_COLOR_BEST_SORE="#fff",FPS_TIME=1E3/30,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_INIT=0,STATE_PLAY=1,STATE_FINISH=2,STATE_PAUSE=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=
4,ON_DRAG_END=5,ON_BUT_NO_DOWN=6,ON_BUT_YES_DOWN=7,NUM_OF_EDGES_FOR_STACK=4,SHOW_EDGES=!0,SHOW_FILL=!0,LEFT_UP=3,RIGHT_UP=2,LEFT_DOWN=1,RIGHT_DOWN=0,NO_DIR=4,EDGE_RIGHT_UP=0,EDGE_RIGHT_DOWN=1,EDGE_LEFT_DOWN=2,EDGE_LEFT_UP=3,STACK_DIRECTIONS={x:.5,y:.5},MS_FADE_ANIM=250,MS_SCROLL_CONTAINER_STACK=750,MS_PERFECT_TEXT=1E3,PERFECT_TEXT_START_POINT={x:CANVAS_WIDTH_HALF,y:CANVAS_HEIGHT-150},PERFECT_TEXT_END_POINT={x:CANVAS_WIDTH_HALF,y:CANVAS_HEIGHT-300},MS_WAIT_SHOW_GAME_OVER_PANEL=500,PLANES_COLOR_1={r:200,
g:0,b:0,a:1},LINES_COLOR_1={r:0,g:200,b:0,a:1},PLANES_COLOR_2={r:0,g:0,b:200,a:1},LINES_COLOR_2={r:255,g:255,b:0,a:1},MS_TIME_ZOOM_OUT=1E3,MS_TIME_PERFECT_HIT=500,CONTAINER_STACK_POS={x:CANVAS_WIDTH_HALF,y:CANVAS_HEIGHT_HALF},LINES_WIDTH=1,ANGLE_STACK=Math.PI/180*35,DEFAULT_DIR={x:Math.cos(ANGLE_STACK),y:Math.sin(ANGLE_STACK)},DIRECTION_STACKS=[DEFAULT_DIR,{x:-DEFAULT_DIR.x,y:DEFAULT_DIR.y},{x:DEFAULT_DIR.x,y:-DEFAULT_DIR.y},{x:-DEFAULT_DIR.x,y:-DEFAULT_DIR.y},{x:0,y:0}],STACK_DIMENSION={x:200,y:140},
STACK_DEPTH_SIZE=50,STACK_HEIGHT_OFFSET=100,STACK_HEIGHT_OFFSET_HALF=.5*STACK_HEIGHT_OFFSET,STACKS_DISTANCE_OFFSET=300,PERFECT_RANGE=1,DEFAULT_COLOR=["#cc0000","#00cc00","#0000cc","#ffff00"],DEPTH_LUMINANCE=-.2,COLOR_GRADIENTS_STACKS="#FF5858 #FF6058 #FF6958 #FF7158 #FF7A58 #FF8358 #FF8B58 #FF9458 #FF9D58 #FFA558 #FFAE58 #FFB658 #FFBF58 #FFC858 #FFD058 #FFD958 #FFE258 #F4E358 #EAE559 #DFE659 #D5E85A #CAEA5B #C0EB5B #B5ED5C #ABEF5D #A0F05D #96F25E #8BF35E #81F55F #76F760 #6CF860 #61FA61 #57FC62 #5AF26B #5DE975 #60E07E #64D788 #67CE91 #6AC49B #6DBBA4 #71B2AE #74A9B7 #77A0C1 #7A96CA #7E8DD4 #8184DD #847BE7 #8772F0 #8B69FA #9267EF #9A66E4 #A265D9 #A964CE #B163C4 #B962B9 #C161AE #C85FA3 #D05E98 #D85D8E #E05C83 #E75B78 #EF5A6D #F75962 #FF5858".split(" "),
SHOW_CUT_EDGES=!1,STACKS_LIMIT_POSITION=[{x:966,y:620},{x:425,y:598},{x:942,y:236.5},{x:426,y:242}],STACKS_START_POSITION=[{x:426,y:242,dir:LEFT_UP},{x:942,y:236.5,dir:LEFT_DOWN}],START_EDGES_POSITION=[{startX:0,startY:-STACK_DIMENSION.y,endX:STACK_DIMENSION.x,endY:0,type:EDGE_RIGHT_UP},{startX:STACK_DIMENSION.x,startY:0,endX:0,endY:STACK_DIMENSION.y,type:EDGE_RIGHT_DOWN},{startX:0,startY:STACK_DIMENSION.y,endX:-STACK_DIMENSION.x,endY:0,type:EDGE_LEFT_DOWN},{startX:-STACK_DIMENSION.x,startY:0,endX:0,
endY:-STACK_DIMENSION.y,type:EDGE_LEFT_UP}],SOUNDTRACK_VOLUME_IN_GAME=.3,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;TEXT_GAMEOVER="GAME OVER";TEXT_CREDITS_DEVELOPED="DEVELOPED BY";TEXT_SCORE="SCORE";TEXT_BEST_SCORE="BEST SCORE";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_PERFECT="PERFECT";var TEXT_PRELOADER_CONTINUE="START";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CPreloader(){var a,d,c,e,b,g,f,n,q,k;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.loadSprites();k=new createjs.Container;s_oStage.addChild(k)};this.unload=function(){k.removeAllChildren();q.unload()};this._onImagesLoaded=function(){};
this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var p=new createjs.Shape;p.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.addChild(p);p=s_oSpriteLibrary.getSprite("200x200");f=createBitmap(p);f.regX=.5*p.width;f.regY=.5*p.height;f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-180;k.addChild(f);n=new createjs.Shape;n.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(f.x-100,f.y-100,200,200,10);k.addChild(n);f.mask=n;
p=s_oSpriteLibrary.getSprite("progress_bar");e=createBitmap(p);e.x=CANVAS_WIDTH/2-p.width/2;e.y=CANVAS_HEIGHT/2+50;k.addChild(e);a=p.width;d=p.height;b=new createjs.Shape;b.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(e.x,e.y,1,d);k.addChild(b);e.mask=b;c=new createjs.Text("","30px "+FONT_GAME,"#fff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2+100;c.textBaseline="alphabetic";c.textAlign="center";k.addChild(c);p=s_oSpriteLibrary.getSprite("but_start");q=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/
2,p,TEXT_PRELOADER_CONTINUE,"Arial","#000",40,k);q.addEventListener(ON_MOUSE_UP,this._onButStartRelease,this);q.setVisible(!1);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.addChild(g);createjs.Tween.get(g).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(g);k.removeChild(g)})};this._onButStartRelease=function(){s_oMain._onRemovePreloader()};this.refreshLoader=function(f){c.text=f+"%";100===f&&(s_oMain._onRemovePreloader(),c.visible=!1,
e.visible=!1);b.graphics.clear();f=Math.floor(f*a/100);b.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(e.x,e.y,f,d)};this._init()}
function CMain(a){var d,c=0,e=0,b=STATE_LOADING,g,f;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_oStage.preventSelection=!1;s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.framerate=30;navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader;d=!0};this.soundLoaded=function(){c++;g.refreshLoader(Math.floor(c/e*100))};this._initSounds=function(){Howler.mute(!s_bAudioActive);s_aSoundsInfo=[];s_aSoundsInfo.push({path:"./sounds/",filename:"cut",loop:!1,volume:1,ingamename:"cut"});s_aSoundsInfo.push({path:"./sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});s_aSoundsInfo.push({path:"./sounds/",filename:"game_over",loop:!1,volume:1,ingamename:"game_over"});
s_aSoundsInfo.push({path:"./sounds/",filename:"perfect",loop:!1,volume:1,ingamename:"perfect"});s_aSoundsInfo.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});e+=s_aSoundsInfo.length;s_aSounds=[];for(var a=0;a<s_aSoundsInfo.length;a++)this.tryToLoadSound(s_aSoundsInfo[a],!1)};this.tryToLoadSound=function(a,b){setTimeout(function(){s_aSounds[a.ingamename]=new Howl({src:[a.path+a.filename+".mp3"],autoplay:!1,preload:!0,loop:a.loop,volume:a.volume,onload:s_oMain.soundLoaded,
onloaderror:function(a,b){for(var c=0;c<s_aSoundsInfo.length;c++)if(a===s_aSounds[s_aSoundsInfo[c].ingamename]._sounds[0]._id){s_oMain.tryToLoadSound(s_aSoundsInfo[c],!0);break}},onplayerror:function(a){for(var b=0;b<s_aSoundsInfo.length;b++)if(a===s_aSounds[s_aSoundsInfo[b].ingamename]._sounds[0]._id){s_aSounds[s_aSoundsInfo[b].ingamename].once("unlock",function(){s_aSounds[s_aSoundsInfo[b].ingamename].play();"soundtrack"===s_aSoundsInfo[b].ingamename&&null!==s_oGame&&setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME)});
break}}})},b?200:0)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("but_restart_small","./sprites/but_restart_small.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");
s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_go","./sprites/but_go.png");s_oSpriteLibrary.addSprite("but_no","./sprites/but_no.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");
s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("logo_menu","./sprites/logo_menu.png");s_oSpriteLibrary.addSprite("bg_score","./sprites/bg_score.png");s_oSpriteLibrary.addSprite("bg_bestscore","./sprites/bg_bestscore.png");e+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){c++;g.refreshLoader(Math.floor(c/e*100))};this._onAllImagesLoaded=function(){};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||this._initSounds();d=!0};this._onRemovePreloader=function(){g.unload();s_oSoundTrack=playSound("soundtrack",1,!0);this.gotoMenu()};this.gotoMenu=function(){new CMenu;b=STATE_MENU};this.gotoGame=function(){f=new CGame(n);b=STATE_GAME};this.gotoHelp=function(){new CHelp;b=STATE_HELP};this.gotoCongratulations=function(a,c){new CCongratulations(a,c);b=STATE_MENU};this.stopUpdate=function(){d=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();d=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(a){if(!1!==d){var c=(new Date).getTime();s_iTimeElaps=c-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=c;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);b===STATE_GAME&&f.update();s_oStage.update(a)}};s_oMain=
this;var n=a;ENABLE_CHECK_ORIENTATION=n.check_orientation;ENABLE_FULLSCREEN=a.fullscreen;s_bAudioActive=a.audio_enable_on_startup;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_bFullscreen=!1,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oAdsLevel=1,s_iBestScore,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null,s_aSounds,s_aSoundsInfo;
function CTextButton(a,d,c,e,b,g,f,n){var q,k,p,l,m;this._init=function(a,b,c,d,e,f,g){q=[];k=[];var l=createBitmap(c);d=new createjs.Text(d,"bold "+g+"px "+e,f);d.textAlign="center";d.textBaseline="alphabetic";e=d.getBounds();d.x=c.width/2;d.y=Math.floor(c.height/2)+e.height/3;m=new createjs.Container;m.x=a;m.y=b;m.regX=c.width/2;m.regY=c.height/2;m.addChild(l,d);s_bMobile||(m.cursor="pointer");u.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown",p);m.off("pressup",l);u.removeChild(m)};
this.setVisible=function(a){m.visible=a};this._initListener=function(){p=m.on("mousedown",this.buttonDown);l=m.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){q[a]=b;k[a]=c};this.buttonRelease=function(){m.scaleX=1;m.scaleY=1;playSound("click",1,!1);q[ON_MOUSE_UP]&&q[ON_MOUSE_UP].call(k[ON_MOUSE_UP])};this.buttonDown=function(){m.scaleX=.9;m.scaleY=.9;q[ON_MOUSE_DOWN]&&q[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setPosition=function(a,b){m.x=a;m.y=b};this.setX=function(a){m.x=
a};this.setY=function(a){m.y=a};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};var u=n;this._init(a,d,c,e,b,g,f);return this}
function CToggle(a,d,c,e,b){var g,f,n,q,k,p,l;this._init=function(a,b,c,d,e){l=void 0!==e?e:s_oStage;f=[];n=[];e=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});g=d;p=createSprite(e,"state_"+g,c.width/2/2,c.height/2,c.width/2,c.height);p.x=a;p.y=b;p.stop();s_bMobile||(p.cursor="pointer");l.addChild(p);this._initListener()};this.unload=function(){p.off("mousedown",q);p.off("pressup",k);l.removeChild(p)};
this._initListener=function(){q=p.on("mousedown",this.buttonDown);k=p.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;n[a]=c};this.setCursorType=function(a){p.cursor=a};this.setActive=function(a){g=a;p.gotoAndStop("state_"+g)};this.buttonRelease=function(){p.scaleX=1;p.scaleY=1;playSound("click",1,!1);g=!g;p.gotoAndStop("state_"+g);f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(n[ON_MOUSE_UP],g)};this.buttonDown=function(){p.scaleX=.9;p.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN])};
this.setPosition=function(a,b){p.x=a;p.y=b};this._init(a,d,c,e,b)}
function CGfxButton(a,d,c,e){var b,g,f,n,q,k,p,l,m=!1;this._init=function(a,c,d){b=[];g=[];f=createBitmap(d);f.x=a;f.y=c;k=q=1;f.regX=d.width/2;f.regY=d.height/2;s_bMobile||(f.cursor="pointer");u.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",p);f.off("pressup",l);u.removeChild(f)};this.setVisible=function(a){f.visible=a};this.setCursorType=function(a){f.cursor=a};this._initListener=function(){p=f.on("mousedown",this.buttonDown);l=f.on("pressup",this.buttonRelease)};this.addEventListener=
function(a,c,d){b[a]=c;g[a]=d};this.addEventListenerWithParams=function(a,c,d,e){b[a]=c;g[a]=d;n=e};this.buttonRelease=function(){m||(f.scaleX=0<q?1:-1,f.scaleY=1,playSound("click",1,!1),b[ON_MOUSE_UP]&&b[ON_MOUSE_UP].call(g[ON_MOUSE_UP],n))};this.buttonDown=function(){m||(f.scaleX=0<q?.9:-.9,f.scaleY=.9,b[ON_MOUSE_DOWN]&&b[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],n))};this.rotation=function(a){f.rotation=a};this.getButton=function(){return f};this.setPosition=function(a,b){f.x=a;f.y=b};this.setX=function(a){f.x=
a};this.setY=function(a){f.y=a};this.getButtonImage=function(){return f};this.block=function(a){m=a;f.scaleX=q;f.scaleY=k};this.setScaleX=function(a){q=f.scaleX=a};this.getX=function(){return f.x};this.getY=function(){return f.y};this.pulseAnimation=function(){createjs.Tween.get(f).to({scaleX:.9*q,scaleY:.9*k},850,createjs.Ease.quadOut).to({scaleX:q,scaleY:k},650,createjs.Ease.quadIn).call(function(){w.pulseAnimation()})};this.trebleAnimation=function(){createjs.Tween.get(f).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},
140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){w.trebleAnimation()})};this.removeAllTweens=function(){createjs.Tween.removeTweens(f)};var u=e;this._init(a,d,c);var w=this;return this}
function CMenu(){var a,d,c,e,b,g,f,n,q,k,p,l,m,u,w,z,B,x=null,E=null,G;this._init=function(){s_iBestScore=getItem("box_best_score");null===s_iBestScore&&(s_iBestScore=0);var y=Math.floor(Math.random()*COLOR_GRADIENTS_STACKS.length);q=new createjs.Shape;q.graphics.beginFill(COLOR_GRADIENTS_STACKS[y]).drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(q);k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(k);z=new createjs.Container;s_oStage.addChild(z);for(var A=[],F=0;F<
NUM_OF_EDGES_FOR_STACK;F++)A.push(new CEdge(1.3*START_EDGES_POSITION[F].startX,1.3*START_EDGES_POSITION[F].startY,1.3*START_EDGES_POSITION[F].endX,1.3*START_EDGES_POSITION[F].endY));y+=32;y>=COLOR_GRADIENTS_STACKS.length&&(y-=COLOR_GRADIENTS_STACKS.length);F=CANVAS_WIDTH_HALF-122;var H=CANVAS_HEIGHT_HALF+30;new CStack({x:F+(1.3*DIRECTION_STACKS[2].x*STACK_DIMENSION.x+STACK_DEPTH_SIZE-19.5),y:H+(1.3*DIRECTION_STACKS[2].y*STACK_DIMENSION.y-12*1.3)-STACK_DEPTH_SIZE,dir:NO_DIR},{line:COLOR_GRADIENTS_STACKS[y],
plane:COLOR_GRADIENTS_STACKS[y],width:LINES_WIDTH,depth:null},A,z);new CStack({x:F,y:H,dir:NO_DIR},{line:COLOR_GRADIENTS_STACKS[y],plane:COLOR_GRADIENTS_STACKS[y],width:LINES_WIDTH,depth:null},A,z);A=s_oSpriteLibrary.getSprite("logo_menu");G=createBitmap(A);G.x=CANVAS_WIDTH_HALF+56;G.y=.5*-A.width;G.regX=.5*A.width;G.regY=.5*A.height;G.rotation=-15;s_oStage.addChild(G);A=s_oSpriteLibrary.getSprite("but_play");b=CANVAS_WIDTH/2;g=CANVAS_HEIGHT-435;p=new CGfxButton(b,g,A,s_oStage);p.addEventListener(ON_MOUSE_UP,
this._onButPlayRelease,this);p.pulseAnimation();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)A=s_oSpriteLibrary.getSprite("audio_icon"),f=CANVAS_WIDTH-A.height/2-15,n=A.height/2+15,u=new CToggle(f,n,A,s_bAudioActive,s_oStage),u.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);A=s_oSpriteLibrary.getSprite("but_info");c=A.height/2+17;e=A.height/2+15;l=new CGfxButton(c,e,A,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onButInfoRelease,this);A=window.document;y=A.documentElement;x=y.requestFullscreen||
y.mozRequestFullScreen||y.webkitRequestFullScreen||y.msRequestFullscreen;E=A.exitFullscreen||A.mozCancelFullScreen||A.webkitExitFullscreen||A.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(x=!1);x&&screenfull.isEnabled&&(A=s_oSpriteLibrary.getSprite("but_fullscreen"),a=c+A.width/2+15,d=A.height/2+15,B=new CToggle(a,d,A,s_bFullscreen,s_oStage),B.addEventListener(ON_MOUSE_UP,this._onFullscreen,this));w=new createjs.Container;s_oStage.addChild(w);m=new createjs.Shape;m.graphics.beginFill("black").drawRect(0,
0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(m);createjs.Tween.get(G).wait(300).to({rotation:0},1E3,createjs.Ease.cubicOut);createjs.Tween.get(G).wait(300).to({y:CANVAS_HEIGHT_HALF-96},1E3,createjs.Ease.bounceOut);createjs.Tween.get(m,{override:!0}).to({alpha:0},500,createjs.Ease.cubicOut).call(function(){m.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(b,g){l.setPosition(c+b,e+g);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||u.setPosition(f-b,g+n);x&&screenfull.isEnabled&&
B.setPosition(a+b,d+g)};this.unload=function(){p.unload();p=null;l.unload();l=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)u.unload(),u=null;x&&screenfull.isEnabled&&B.unload();s_oStage.removeAllChildren();s_oMenu=null};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButInfoRelease=function(){new CCreditsPanel};this._onButPlayRelease=function(){this.fadeAnim()};this.resetFullscreenBut=function(){x&&screenfull.isEnabled&&B.setActive(s_bFullscreen)};
this._onFullscreen=function(){s_bFullscreen?E.call(window.document):x.call(window.document.documentElement);sizeHandler()};this.fadeAnim=function(){var a=this;m.visible=!0;createjs.Tween.get(m,{override:!0}).to({alpha:1},MS_FADE_ANIM,createjs.Ease.cubicIn).call(function(){a.unload();s_oMain.gotoGame()})};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var d,c;function e(a){f||q!==STATE_PLAY||32!==a.keyCode||(s_oGame.onMouseDown(),f=!0);a.preventDefault();return!1}function b(a){32===a.keyCode&&(f=!1);a.preventDefault();return!1}var g=!0,f=!1,n=0,q=STATE_PAUSE,k=1,p,l,m,u=0,w,z,B,x,E,G,y,A,F;this._init=function(){$(s_oMain).trigger("start_session");$(s_oMain).trigger("start_level",1);F=[];this.restartColorGrandients();z=new createjs.Shape;z.graphics.beginFill(COLOR_GRADIENTS_STACKS[m]).drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);z.cache(0,
0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(z);var a=s_oSpriteLibrary.getSprite("bg_game");B=createBitmap(a);s_oStage.addChild(B);B.cache(0,0,a.width,a.height);E=new createjs.Container;E.tickChildren=!1;this.resetContainerStacks();s_oStage.addChild(E);A=new createjs.Shape;A.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);A.on("mousedown",this.onMouseDown);s_oStage.addChild(A);w=new CInterface;w.refreshScoreText(n);w.refreshBestScore(s_iBestScore,!1);this.createStartStacks();
x=new createjs.Shape;x.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c=d=0;s_oStage.addChild(x);s_bMobile||(document.onkeydown=e,document.onkeyup=b);this.startFade()};this.restartColorGrandients=function(){l=Math.floor(Math.random()*COLOR_GRADIENTS_STACKS.length);m=l+10;m>=COLOR_GRADIENTS_STACKS.length&&(m-=COLOR_GRADIENTS_STACKS.length)};this.startFade=function(){x.visible=!0;x.alpha=1;createjs.Tween.get(x).to({alpha:0},MS_FADE_ANIM,createjs.Ease.cubicOut).call(function(){x.visible=
!1})};this.resetContainerStacks=function(){E.x=CANVAS_WIDTH_HALF;E.y=CANVAS_HEIGHT;E.regX=CANVAS_WIDTH_HALF;E.regY=CANVAS_HEIGHT;E.scaleX=E.scaleY=1;p=E.y};this.createStartStacks=function(){for(var a=[],b=0;b<NUM_OF_EDGES_FOR_STACK;b++)a.push(new CEdge(START_EDGES_POSITION[b].startX,START_EDGES_POSITION[b].startY,START_EDGES_POSITION[b].endX,START_EDGES_POSITION[b].endY));G=new CStack({x:CANVAS_WIDTH_HALF,y:CANVAS_HEIGHT_HALF+150,dir:NO_DIR},{line:COLOR_GRADIENTS_STACKS[l],plane:COLOR_GRADIENTS_STACKS[l],
width:LINES_WIDTH,depth:null},a,E);G.setID(0);F.push(G);this.nextColorGradient();y=new CStack({x:STACKS_START_POSITION[k].x,y:STACKS_START_POSITION[k].y-STACK_DEPTH_SIZE,dir:STACKS_START_POSITION[k].dir},{line:COLOR_GRADIENTS_STACKS[l],plane:COLOR_GRADIENTS_STACKS[l],width:LINES_WIDTH,depth:null},a,E);y.setID(1);a=G.getPos();a.y-=STACK_DEPTH_SIZE;y.setLimitPosition(this.getLimitPos(a));y.setPosition(y.getLimitPosition(3-k).x,y.getLimitPosition(3-k).y);this.nextColorGradient();F.push(y)};this.zoomOutContainerStacks=
function(){var a=1/(.06*n);1<a&&(a=1);var b=E.y+(F[Math.floor(F.length-1)].getPos().y-F[0].getPos().y);createjs.Tween.get(E).to({scaleX:a,scaleY:a,y:b},MS_TIME_ZOOM_OUT,createjs.Ease.quartOut)};this.gameOver=function(){q=STATE_FINISH;y.fallEffect();this.zoomOutContainerStacks();this.visibleAllStacks();n>s_iBestScore&&(s_iBestScore=n,saveItem("box_best_score",n));playSound("game_over",1,!1);w.createWinPanel(n)};this.onMouseDown=function(){y.updateEdgesPosition();var a=s_oGame.intersectionPointsStacks(G,
y);!1===a.result?q===STATE_PLAY&&s_oGame.gameOver():(s_oGame.nextColorGradient(),s_oGame.moveContainerStack(),y.updateSize(),y.cacheStack(),s_oGame.changeDirStack(),s_oGame.createNewStack(y.getEdges(),a.point,a.cut),s_oGame.addScore(1),s_oGame.animPerfectText(a.cut),s_oGame.checkVisibleStack())};this.animPerfectText=function(a){a||w.animPerfectText()};this.nextColorGradient=function(){l++;m++;l===COLOR_GRADIENTS_STACKS.length&&(l=0);m===COLOR_GRADIENTS_STACKS.length&&(m=0);z.graphics.clear();z.graphics.beginFill(COLOR_GRADIENTS_STACKS[m]).drawRect(0,
0,CANVAS_WIDTH,CANVAS_HEIGHT).endFill();z.updateCache()};this.checkVisibleStack=function(){for(var a=u;a<F.length;a++)if(F[a].isVisible()&&F[a].getPosLocal().y>CANVAS_HEIGHT){F[a].setVisible(!1);u=a;break}};this.visibleAllStacks=function(){for(var a=0;a<F.length;a++)F[a].setVisible(!0)};this.addScore=function(a){n+=a;w.refreshScoreText(n);n>s_iBestScore&&w.refreshBestScore(n,!0)};this.intersectionPointsStacks=function(a,b){var c=1;if(b.getDirID()===LEFT_UP||b.getDirID()===RIGHT_DOWN)c=0;if(0===c){var d=
a.getLeftDownAndRightUpEdges();var e=b.getLeftDownAndRightUpEdges();var f=b.getLeftUpAndRightDownEdges()}else d=a.getLeftUpAndRightDownEdges(),e=b.getLeftUpAndRightDownEdges(),f=b.getLeftDownAndRightUpEdges();var g=this.checkIntersectionPoint(d[0],e[0]);var l=this.checkIntersectionPoint(d[1],e[1]);if(0===l.result||1===l.result||0===g.result||1===g.result)return{result:!1};d=e[0].getPointA().getX()-g.vec1.getX();var m=e[1].getPointA().getX()-l.vec1.getX(),k=e[0].getPointA().getY()-g.vec1.getY(),n=
e[1].getPointA().getY()-l.vec1.getY(),v=e[0].getPointB().getX()-g.vec2.getX(),h=e[1].getPointB().getX()-l.vec2.getX();g=e[0].getPointB().getY()-g.vec2.getY();l=e[1].getPointB().getY()-l.vec2.getY();var p={x:0,y:0},x=!1,q=!1;if(0===c)if(0!==d&&0!==h){if(p={x:d,y:k},Math.abs(d)>PERFECT_RANGE&&Math.abs(h)>PERFECT_RANGE){q=!0;var H=f[1];var u=new CEdge(f[1].getPointB().getX(),f[1].getPointB().getY(),f[1].getPointA().getX(),f[1].getPointA().getY(),f[1].getInfo());this.newEdgesPosition({right:e[0],left:e[1],
distance:f[1],point1:{x:d,y:k},point2:{x:h,y:l}});x=!0}}else 0!==v&&0!==m&&(p={x:m,y:n},Math.abs(v)>PERFECT_RANGE&&Math.abs(m)>PERFECT_RANGE&&(H=f[0],u=new CEdge(f[0].getPointB().getX(),f[0].getPointB().getY(),f[0].getPointA().getX(),f[0].getPointA().getY(),f[0].getInfo()),this.newEdgesPosition({right:e[1],left:e[0],distance:f[0],point1:{x:v,y:g},point2:{x:m,y:n}}),x=!0));else 0!==d&&0!==h?(p={x:h,y:l},Math.abs(d)>PERFECT_RANGE&&Math.abs(h)>PERFECT_RANGE&&(H=f[0],u=new CEdge(f[0].getPointB().getX(),
f[0].getPointB().getY(),f[0].getPointA().getX(),f[0].getPointA().getY(),f[0].getInfo()),this.newEdgesPosition({right:e[0],left:e[1],distance:f[0],point1:{x:d,y:k},point2:{x:h,y:l}}),x=!0)):0!==v&&0!==m&&(q=!0,p={x:v,y:g},Math.abs(v)>PERFECT_RANGE&&Math.abs(m)>PERFECT_RANGE&&(u=new CEdge(f[1].getPointB().getX(),f[1].getPointB().getY(),f[1].getPointA().getX(),f[1].getPointA().getY(),f[1].getInfo()),H=f[1],this.newEdgesPosition({right:e[1],left:e[0],distance:f[1],point1:{x:v,y:g},point2:{x:m,y:n}}),
x=!0));x&&this.cutStack(H,u,p,q);return{result:!0,point:p,cut:x}};this.cutStack=function(a,b,c,d){var e=[];switch(y.getDirID()){case 0:case 3:d?(e.push(new CEdge(b.getPointA().getX(),b.getPointA().getY(),a.getPointB().getX(),a.getPointB().getY())),e.push(new CEdge(a.getPointB().getX(),a.getPointB().getY(),a.getPointA().getX(),a.getPointA().getY())),e.push(new CEdge(a.getPointA().getX(),a.getPointA().getY(),b.getPointB().getX(),b.getPointB().getY())),e.push(new CEdge(b.getPointB().getX(),b.getPointB().getY(),
b.getPointA().getX(),b.getPointA().getY()))):(e.push(new CEdge(a.getPointA().getX(),a.getPointA().getY(),b.getPointB().getX(),b.getPointB().getY())),e.push(new CEdge(b.getPointB().getX(),b.getPointB().getY(),b.getPointA().getX(),b.getPointA().getY())),e.push(new CEdge(b.getPointA().getX(),b.getPointA().getY(),a.getPointB().getX(),a.getPointB().getY())),e.push(new CEdge(a.getPointB().getX(),a.getPointB().getY(),a.getPointA().getX(),a.getPointA().getY())));break;case 1:case 2:d?(e.push(new CEdge(a.getPointB().getX(),
a.getPointB().getY(),a.getPointA().getX(),a.getPointA().getY())),e.push(new CEdge(a.getPointA().getX(),a.getPointA().getY(),b.getPointB().getX(),b.getPointB().getY())),e.push(new CEdge(b.getPointB().getX(),b.getPointB().getY(),b.getPointA().getX(),b.getPointA().getY())),e.push(new CEdge(b.getPointA().getX(),b.getPointA().getY(),a.getPointB().getX(),a.getPointB().getY()))):(e.push(new CEdge(b.getPointB().getX(),b.getPointB().getY(),b.getPointA().getX(),b.getPointA().getY())),e.push(new CEdge(b.getPointA().getX(),
b.getPointA().getY(),a.getPointB().getX(),a.getPointB().getY())),e.push(new CEdge(a.getPointB().getX(),a.getPointB().getY(),a.getPointA().getX(),a.getPointA().getY())),e.push(new CEdge(a.getPointA().getX(),a.getPointA().getY(),b.getPointB().getX(),b.getPointB().getY())))}a={x:y.getPos().x,y:y.getPos().y,dir:NO_DIR};if(SHOW_CUT_EDGES)for(b=0;b<e.length;b++){d=new createjs.Shape;d.graphics.beginStroke(DEFAULT_COLOR[b]);d.graphics.setStrokeStyle(LINES_WIDTH);d.graphics.moveTo(e[b].getPointA().getX(),
e[b].getPointA().getY());d.graphics.lineTo(e[b].getPointB().getX(),e[b].getPointB().getY());var f=new createjs.Shape;f.graphics.beginFill("#fff").drawCircle(e[b].getPointA().getX(),e[b].getPointA().getY(),10);var g=new createjs.Shape;g.graphics.beginFill("#000").drawCircle(e[b].getPointB().getX(),e[b].getPointB().getY(),10);E.addChild(d,g,f)}e=this.createStack(e,{x:0,y:0},a,y.getColor());0>c.x&&0>c.y?e.setChildIndex(0):0<c.x&&0>c.y&&e.setChildIndex(0);e.fallEffect()};this.newEdgesPosition=function(a){a.right.set(a.right.getPointA().getX()-
a.point1.x,a.right.getPointA().getY()-a.point1.y,a.right.getPointB().getX(),a.right.getPointB().getY());a.left.set(a.left.getPointA().getX(),a.left.getPointA().getY(),a.left.getPointB().getX()-a.point2.x,a.left.getPointB().getY()-a.point2.y);a.distance.set(a.left.getPointB().getX(),a.left.getPointB().getY(),a.right.getPointA().getX(),a.right.getPointA().getY())};this.checkIntersectionPoint=function(a,b){var c=new CVector2(0,0),d=new CVector2(0,0),e=new CEdge(a.getPointA().getX()+0,a.getPointA().getY()+
0,a.getPointB().getX()+0,a.getPointB().getY()+0);e=intersect2D_Segments(e,b,c,d);return{vec1:c,vec2:d,result:e}};this.createNewStack=function(a,b,e){e?(playSound("cut",1,!1),e={x:y.getPos().x-b.x,y:y.getPos().y-STACK_DEPTH_SIZE-b.y,dir:STACKS_START_POSITION[k].dir}):(playSound("perfect",1,!1),y.perfectPosition(),y.setPosition(G.getPos().x-d,G.getPos().y-c-STACK_DEPTH_SIZE),y.updateEdgesPosition(),e={x:y.getPos().x+d-b.x,y:y.getPos().y-STACK_DEPTH_SIZE+c-b.y,dir:STACKS_START_POSITION[k].dir});d=b.x;
c=b.y;a=this.createStack(a,b,e,{line:COLOR_GRADIENTS_STACKS[l],plane:COLOR_GRADIENTS_STACKS[l],width:LINES_WIDTH,depth:null});a.setLimitPosition(this.getLimitPos(e));a.setPosition(a.getLimitPosition(3-k).x,a.getLimitPosition(3-k).y);F.push(a);G=y;y=a};this.createStack=function(a,b,c,d){for(var e=y.getPos(),f=[],g=0;g<a.length;g++)f[g]=new CEdge(a[g].getPointA().getX()-e.x+b.x,a[g].getPointA().getY()-e.y+b.y,a[g].getPointB().getX()-e.x+b.x,a[g].getPointB().getY()-e.y+b.y,START_EDGES_POSITION[g].type);
return new CStack(c,d,f,E)};this.changeDirStack=function(){1===k?k=0:k++};this.moveContainerStack=function(){p+=STACK_DEPTH_SIZE;createjs.Tween.get(E,{override:!0}).to({y:p},MS_SCROLL_CONTAINER_STACK,createjs.Ease.cubicOut).call(function(){},null,this)};this.getLimitPos=function(a){for(var b=[],c=0;c<STACKS_LIMIT_POSITION.length;c++)b.push({x:a.x+DIRECTION_STACKS[c].x*STACKS_DISTANCE_OFFSET,y:a.y+DIRECTION_STACKS[c].y*STACKS_DISTANCE_OFFSET});return b};this.unload=function(){g=!1;w.unload();s_oStage.removeAllChildren();
createjs.Tween.removeAllTweens()};this.onExit=function(){$(s_oMain).trigger("end_session");$(s_oMain).trigger("end_level",1);var a=this;x.visible=!0;createjs.Tween.get(x,{override:!0}).to({alpha:1},MS_FADE_ANIM,createjs.Ease.cubicOut).call(function(){$(s_oMain).trigger("show_interlevel_ad");a.unload();setVolume("soundtrack",1);s_oMain.gotoMenu()})};this._onStart=function(){q=STATE_PLAY;setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME)};this.restartGame=function(){x.visible=!0;createjs.Tween.get(x,
{ignoreGlobalPause:!0,override:!0}).to({alpha:1},MS_FADE_ANIM,createjs.Ease.cubicOut).call(function(){for(var a=0;a<F.length;a++)F[a].unload();F=[];s_oGame.resetContainerStacks();G=null;n=c=d=0;w.refreshScoreText(n);s_oGame.restartColorGrandients();s_oGame.createStartStacks();s_oGame.startFade();w.refreshBestScore(s_iBestScore,!1);q=STATE_PLAY})};this.unpause=function(a){g=a};this._onEnd=function(){x.visible=!0;createjs.Tween.get(x,{ignoreGlobalPause:!0}).to({alpha:1},MS_FADE_ANIM,createjs.Ease.cubicOut).call(function(){s_oGame.unload();
$(s_oMain).trigger("end_level",1);$(s_oMain).trigger("end_session");setVolume("soundtrack",1);s_oMain.gotoMenu()})};this._updatePlay=function(){g&&y.update(STACK_VELOCITY)};this.update=function(){switch(q){case STATE_PLAY:this._updatePlay()}};s_oGame=this;STACK_VELOCITY=a.stack_velocity;NUM_LEVEL_FOR_ADS=a.num_levels_for_ads;this._init()}var s_oGame;
function CInterface(a,d){var c,e,b,g,f,n,q,k,p,l,m,u,w,z,B,x=null,E=null;this._init=function(){var a=s_oSpriteLibrary.getSprite("but_exit");b=CANVAS_WIDTH-a.height/2-15;g=a.height/2+15;q=new CGfxButton(b,g,a,s_oStage);q.addEventListener(ON_MOUSE_UP,this._onExit,this);a=s_oSpriteLibrary.getSprite("but_restart_small");n={x:b-a.height-15,y:g};k=new CGfxButton(n.x,n.y,a,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onRestart,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(a=s_oSpriteLibrary.getSprite("audio_icon"),
f={x:n.x-a.height-15,y:g},m=new CToggle(f.x,f.y,a,s_bAudioActive,s_oStage),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this)):f=n;a=window.document;var d=a.documentElement;x=d.requestFullscreen||d.mozRequestFullScreen||d.webkitRequestFullScreen||d.msRequestFullscreen;E=a.exitFullscreen||a.mozCancelFullScreen||a.webkitExitFullscreen||a.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(x=!1);x&&screenfull.isEnabled&&(a=s_oSpriteLibrary.getSprite("but_fullscreen"),c=f.x-a.width/2-15,e=g,B=new CToggle(c,
e,a,s_bFullscreen,s_oStage),B.addEventListener(ON_MOUSE_UP,this._onFullscreen,this));w=new CScoreBoard(s_oStage);z=new CTextPerfect(s_oStage);this.createButStart();this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.createButStart=function(){l=new createjs.Shape;l.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l.on("click",function(){});s_oStage.addChild(l);var a=s_oSpriteLibrary.getSprite("but_go");p=new CGfxButton(CANVAS_WIDTH_HALF,CANVAS_HEIGHT_HALF,a,s_oStage);
p.addEventListener(ON_MOUSE_UP,this._onMouseUpStart,this);p.pulseAnimation()};this.refreshButtonPos=function(a,d){q.setPosition(b-a,d+g);k.setPosition(n.x-a,d+n.y);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(f.x-a,d+f.y);var l=w.getStartPosScore();w.setPosScore(l.x+a,l.y+d);x&&screenfull.isEnabled&&B.setPosition(c-a,e+d);z.updatePoints(a,d)};this._onMouseUpStart=function(){l.removeAllEventListeners();s_oStage.removeChild(l);s_oGame._onStart();p.unload();p=null};this.unload=function(){q.unload();
q=null;k.unload();k=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m.unload(),m=null;x&&screenfull.isEnabled&&B.unload();s_oInterface=null};this.createWinPanel=function(a){u=new CWinPanel(s_oSpriteLibrary.getSprite("msg_box"));u.show(a)};this.refreshScoreText=function(a){w.refreshTextScore(a)};this.refreshBestScore=function(a,b){w.refreshTextBestScore(a,b)};this.animPerfectText=function(){z.animText()};this.refreshLevelText=function(a){(void 0).refreshTextLevel(a)};this.subEffect=function(a){w.effectSubtractScore(a)};
this.resetFullscreenBut=function(){x&&screenfull.isEnabled&&B.setActive(s_bFullscreen)};this._onFullscreen=function(){s_bFullscreen?E.call(window.document):x.call(window.document.documentElement);sizeHandler()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){(new CAreYouSurePanel(s_oStage)).show()};this.blockCommand=function(a){s_bMobile&&(void 0).block(a)};this._onRestart=function(){s_oGame.restartGame()};s_oInterface=this;this._init(a,
d);return this}var s_oInterface=null;
function CWinPanel(a,d){var c,e,b,g,f,n,q,k,p,l,m;this._init=function(a){k=new createjs.Container;k.alpha=0;k.visible=!1;var d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=.5;k.addChild(d);c=createBitmap(a);c.x=CANVAS_WIDTH_HALF;c.y=CANVAS_HEIGHT_HALF;c.regX=.5*a.width;c.regY=.5*a.height;k.addChild(c);e=new CTLText(k,CANVAS_WIDTH/2-300,CANVAS_HEIGHT/2-200,600,100,100,"center",TEXT_COLOR_STROKE,FONT_GAME,1,0,0," ",!0,!0,!1,!1);e.setOutline(5);b=
new CTLText(k,CANVAS_WIDTH/2-300,CANVAS_HEIGHT/2-200,600,100,100,"center",TEXT_COLOR,FONT_GAME,1,0,0," ",!0,!0,!1,!1);g=new CTLText(k,CANVAS_WIDTH/2-300,CANVAS_HEIGHT_HALF-50,600,50,50,"center",TEXT_COLOR_STROKE,FONT_GAME,1,0,0," ",!0,!0,!1,!1);g.setOutline(5);f=new CTLText(k,CANVAS_WIDTH/2-300,CANVAS_HEIGHT_HALF-50,600,50,50,"center",TEXT_COLOR,FONT_GAME,1,0,0," ",!0,!0,!1,!1);n=new CTLText(k,CANVAS_WIDTH/2-230,CANVAS_HEIGHT_HALF+50,460,50,50,"center",TEXT_COLOR_STROKE,FONT_GAME,1,0,0," ",!0,!0,
!1,!1);n.setOutline(5);q=new CTLText(k,CANVAS_WIDTH/2-230,CANVAS_HEIGHT_HALF+50,460,50,50,"center",TEXT_COLOR,FONT_GAME,1,0,0," ",!0,!0,!1,!1);a=s_oSpriteLibrary.getSprite("but_restart");l=new CGfxButton(.5*CANVAS_WIDTH+290,.5*CANVAS_HEIGHT+130,a,k);l.pulseAnimation();l.addEventListener(ON_MOUSE_DOWN,this._onRestart,this);a=s_oSpriteLibrary.getSprite("but_home");p=new CGfxButton(.5*CANVAS_WIDTH-290,.5*CANVAS_HEIGHT+130,a,k);p.addEventListener(ON_MOUSE_DOWN,this._onExit,this);m=new createjs.Container;
k.addChild(m);k.on("click",function(){});s_oStage.addChild(k)};this.unload=function(){k.removeAllEventListeners();s_oStage.removeChild(k);p&&(p.unload(),p=null);l&&(l.unload(),l=null)};this.show=function(a){e.refreshText(TEXT_GAMEOVER);b.refreshText(TEXT_GAMEOVER);g.refreshText(TEXT_SCORE+": "+a);f.refreshText(TEXT_SCORE+": "+a);n.refreshText(TEXT_BEST_SCORE+": "+s_iBestScore);q.refreshText(TEXT_BEST_SCORE+": "+s_iBestScore);k.visible=!0;createjs.Tween.get(k).wait(MS_WAIT_SHOW_GAME_OVER_PANEL).to({alpha:1},
1250,createjs.Ease.cubicOut).call(function(){s_oAdsLevel===NUM_LEVEL_FOR_ADS?($(s_oMain).trigger("show_interlevel_ad"),s_oAdsLevel=1):s_oAdsLevel++});$(s_oMain).trigger("save_score",a);$(s_oMain).trigger("share_event",a)};this._onContinue=function(){var a=this;createjs.Tween.get(k,{override:!0}).to({alpha:0},750,createjs.Ease.cubicOut).call(function(){a.unload()});_oButContinue.block(!0);p.block(!0);s_oGame.onContinue()};this._onRestart=function(){l.block(!0);this.unload();s_oGame.restartGame()};
this._onExit=function(){this.unload();s_oGame.onExit()};this._init(a,d);return this}var _0x5059="_init;addChild;drawRect;black;beginFill;graphics;alpha;msg_box;getSprite;x;y;regX;width;regY;height;#0f0f0f;click;on;cursor;pointer;secret;but_exit;unload;addEventListener;40px ;textAlign;center;textBaseline;alphabetic;outline;logo_ctl;WWW.CODETHISLAB.COM;50px ;CREATED BY GENNARO PALLADINO EX CODETHISLAB DEVELOPER;lineWidth;getBounds;removeChild;call;cubicOut;Ease;to;wait;bounceOut;get;Tween;off;_onLogoButRelease;http://www.codethislab.com/index.php?&l=en;_blank;open".split(";");
function CCreditsPanel(){var a,d,c,e,b,g,f,n,q,k,p=0;this[_0x5059[0]]=function(){k=new createjs.Container;s_oStage[_0x5059[1]](k);var l=new createjs.Shape;l[_0x5059[5]][_0x5059[4]](_0x5059[3])[_0x5059[2]](0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l[_0x5059[6]]=.6;k[_0x5059[1]](l);l=s_oSpriteLibrary[_0x5059[8]](_0x5059[7]);a=createBitmap(l);a[_0x5059[9]]=CANVAS_WIDTH_HALF;a[_0x5059[10]]=CANVAS_HEIGHT_HALF;a[_0x5059[11]]=.5*l[_0x5059[12]];a[_0x5059[13]]=.5*l[_0x5059[14]];k[_0x5059[1]](a);g=new createjs.Shape;
g[_0x5059[5]][_0x5059[4]](_0x5059[15])[_0x5059[2]](0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g[_0x5059[6]]=.01;g[_0x5059[17]](_0x5059[16],this._onLogoButRelease);g[_0x5059[18]]=_0x5059[19];k[_0x5059[1]](g);l=new createjs.Shape;l[_0x5059[5]][_0x5059[4]](_0x5059[15])[_0x5059[2]](CANVAS_WIDTH-2*EDGEBOARD_X,CANVAS_HEIGHT-2*EDGEBOARD_Y,2*EDGEBOARD_X,2*EDGEBOARD_Y);l[_0x5059[6]]=.01;l[_0x5059[17]](_0x5059[16],this[_0x5059[20]]);l[_0x5059[18]]=_0x5059[19];k[_0x5059[1]](l);l=s_oSpriteLibrary[_0x5059[8]](_0x5059[21]);
q={x:.5*CANVAS_WIDTH+330,y:510};c=new CGfxButton(q[_0x5059[9]],q[_0x5059[10]],l,k);c[_0x5059[23]](ON_MOUSE_UP,this[_0x5059[22]],this);b=new createjs.Text(TEXT_CREDITS_DEVELOPED,_0x5059[24]+FONT_GAME,TEXT_COLOR_STROKE);b[_0x5059[25]]=_0x5059[26];b[_0x5059[27]]=_0x5059[28];b[_0x5059[9]]=CANVAS_WIDTH/2;b[_0x5059[10]]=560;b[_0x5059[29]]=1;k[_0x5059[1]](b);e=new createjs.Text(TEXT_CREDITS_DEVELOPED,_0x5059[24]+FONT_GAME,TEXT_COLOR);e[_0x5059[25]]=_0x5059[26];e[_0x5059[27]]=_0x5059[28];e[_0x5059[9]]=b[_0x5059[9]];
e[_0x5059[10]]=b[_0x5059[10]];k[_0x5059[1]](e);l=s_oSpriteLibrary[_0x5059[8]](_0x5059[30]);d=createBitmap(l);d[_0x5059[11]]=l[_0x5059[12]]/2;d[_0x5059[13]]=l[_0x5059[14]]/2;d[_0x5059[9]]=CANVAS_WIDTH/2;d[_0x5059[10]]=b[_0x5059[10]]+100;k[_0x5059[1]](d);n=new createjs.Text(_0x5059[31],_0x5059[32]+FONT_GAME,TEXT_COLOR_STROKE);n[_0x5059[25]]=_0x5059[26];n[_0x5059[27]]=_0x5059[28];n[_0x5059[9]]=CANVAS_WIDTH/2;n[_0x5059[10]]=b[_0x5059[10]]+240;n[_0x5059[29]]=1;k[_0x5059[1]](n);f=new createjs.Text(_0x5059[31],
_0x5059[32]+FONT_GAME,TEXT_COLOR);f[_0x5059[25]]=_0x5059[26];f[_0x5059[27]]=_0x5059[28];f[_0x5059[9]]=n[_0x5059[9]];f[_0x5059[10]]=n[_0x5059[10]];k[_0x5059[1]](f)};this[_0x5059[20]]=function(){if(5===p){var a=new createjs.Text(_0x5059[33],_0x5059[24]+FONT_GAME,TEXT_COLOR);a[_0x5059[25]]=_0x5059[26];a[_0x5059[27]]=_0x5059[28];a[_0x5059[34]]=500;var b=new createjs.Text(_0x5059[33],_0x5059[24]+FONT_GAME,TEXT_COLOR_STROKE);b[_0x5059[25]]=_0x5059[26];b[_0x5059[27]]=_0x5059[28];b[_0x5059[34]]=500;b[_0x5059[29]]=
1;var c=new createjs.Container;c[_0x5059[1]](a);c[_0x5059[1]](b);c[_0x5059[9]]=CANVAS_WIDTH_HALF;c[_0x5059[10]]=-a[_0x5059[35]]()[_0x5059[14]];k[_0x5059[1]](c);createjs[_0x5059[44]][_0x5059[43]](c)[_0x5059[40]]({y:CANVAS_HEIGHT_HALF+300},1E3,createjs[_0x5059[39]][_0x5059[42]])[_0x5059[41]](3E3)[_0x5059[40]]({alpha:0},1E3,createjs[_0x5059[39]][_0x5059[38]])[_0x5059[37]](function(){k[_0x5059[36]](a);p=0})}p++};this[_0x5059[22]]=function(){g[_0x5059[45]](_0x5059[16],this._onLogoButRelease);c[_0x5059[22]]();
c=null;s_oStage[_0x5059[36]](k)};this[_0x5059[46]]=function(){window[_0x5059[49]](_0x5059[47],_0x5059[48])};this._init()}
function CAreYouSurePanel(a){var d,c,e,b;this._init=function(){b=new createjs.Container;b.alpha=0;g.addChild(b);var a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.alpha=.5;b.addChild(a);a=s_oSpriteLibrary.getSprite("msg_box");var n=createBitmap(a);n.x=CANVAS_WIDTH_HALF;n.y=CANVAS_HEIGHT_HALF;n.regX=.5*a.width;n.regY=.5*a.height;b.addChild(n);d=new CTLText(b,CANVAS_WIDTH/2-300,CANVAS_HEIGHT/2-200,600,160,80,"center",TEXT_COLOR_STROKE,FONT_GAME,1,0,0,TEXT_ARE_SURE,
!0,!0,!0,!1);d.setOutline(3);new CTLText(b,CANVAS_WIDTH/2-300,CANVAS_HEIGHT/2-200,600,160,80,"center",TEXT_COLOR,FONT_GAME,1,0,0,TEXT_ARE_SURE,!0,!0,!0,!1);b.on("click",function(){});c=new CGfxButton(CANVAS_WIDTH/2+280,CANVAS_HEIGHT_HALF+120,s_oSpriteLibrary.getSprite("but_yes"),b);c.addEventListener(ON_MOUSE_UP,this._onButYes,this);e=new CGfxButton(CANVAS_WIDTH/2-280,CANVAS_HEIGHT_HALF+120,s_oSpriteLibrary.getSprite("but_no"),b);e.addEventListener(ON_MOUSE_UP,this._onButNo,this);e.pulseAnimation()};
this.show=function(){s_oGame.unpause(!1);createjs.Tween.get(b,{ignoreGlobalPause:!0}).to({alpha:1},500,createjs.Ease.cubicOut)};this._onButYes=function(){s_oGame.unpause(!0);this.unload();s_oGame.onExit()};this._onButNo=function(){var a=this;createjs.Tween.get(b,{ignoreGlobalPause:!0}).to({alpha:0},500,createjs.Ease.cubicOut).call(function(){s_oGame.unpause(!0);a.unload()})};this.unload=function(){c.unload();c=null;e.unload();e=null;b.removeAllEventListeners();s_oStage.removeChild(b)};var g=a;this._init()}
function CVector2(a,d){var c,e;this._init=function(a,d){c=a;e=d};this.add=function(a,d){c+=a;e+=d};this.addV=function(a){c+=a.getX();e+=a.getY()};this.scalarDivision=function(a){c/=a;e/=a};this.subtract=function(a){c-=a.getX();e-=a.getY()};this.scalarProduct=function(a){c*=a;e*=a};this.invert=function(){c*=-1;e*=-1};this.dotProduct=function(a){return c*a.getX()+e*a.getY()};this.set=function(a,d){c=a;e=d};this.setV=function(a){c=a.getX();e=a.getY()};this.length=function(){return Math.sqrt(c*c+e*e)};
this.length2=function(){return c*c+e*e};this.normalize=function(){var a=this.length();0<a&&(c/=a,e/=a)};this.angleBetweenVectors=function(a){a=Math.acos(this.dotProduct(a)/(this.length()*a.length()));return!0===isNaN(a)?0:a};this.getNormalize=function(a){this.length();a.set(c,e);a.normalize()};this.rot90CCW=function(){var a=c;c=-e;e=a};this.rot90CW=function(){var a=c;c=e;e=-a};this.getRotCCW=function(a){a.set(c,e);a.rot90CCW()};this.getRotCW=function(a){a.set(c,e);a.rot90CW()};this.ceil=function(){c=
Math.ceil(c);e=Math.ceil(e)};this.round=function(){c=Math.round(c);e=Math.round(e)};this.toString=function(){return"Vector2: "+c+", "+e};this.print=function(){trace("Vector2: "+c+", "+e)};this.getX=function(){return c};this.getY=function(){return e};this.rotate=function(a){var b=c,d=e;c=b*Math.cos(a)+d*Math.sin(a);e=b*-Math.sin(a)+d*Math.cos(a)};this._init(a,d)}
function CEdge(a,d,c,e,b){var g=null,f=null,n=null,q=null,k=null,p=null;this._init=function(a,b,c,d,e){this.set(a,b,c,d);p=e};this.destroy=function(){k=q=n=f=g=null};this.render=function(a){a.moveTo(g.x,g.y);a.lineTo(f.x,f.y)};this.toString=function(a){trace(a+" "+g.x+" "+g.y+" "+f.x+" "+f.y)};this.add=function(a){g.addV(a);f.addV(a)};this.set=function(a,b,c,d){g=new CVector2;f=new CVector2;g.set(a,b);f.set(c,d);this.calculateNormal();this.calculateCenter()};this.scale=function(a){g.scalarProduct(a);
f.scalarProduct(a);this.calculateNormal();this.calculateCenter()};this.calculateNormal=function(){k=null;k=new CVector2;k.setV(f);k.subtract(g);k.rot90CCW();k.normalize()};this.calculateCenter=function(){n=null;n=centerBetweenPointsV2(g,f);q=new CVector2;q.setV(k);q.scalarProduct(5);q.addV(n)};this.getPointA=function(){return g};this.m_pCenter=function(){return n};this.getPointB=function(){return f};this.getNormal=function(){return k};this.getInfo=function(){return b};this.toString=function(){return"A: "+
g.toString()+" B: "+f.toString()+" oInfo: "+p};this.renderNormal=function(a){a.moveTo(n.x,n.y);a.lineTo(q.x,q.y)};this._init(a,d,c,e,b);return this}
function CScoreBoard(a){var d,c,e,b,g,f,n,q,k,p;this._init=function(){q=new createjs.Container;k=new createjs.Container;k.x=-360;k.y=120;d={x:.5*CANVAS_WIDTH,y:61};n=new createjs.Container;n.x=d.x;n.y=d.y;a.addChild(n);n.addChild(k,q);b=new createjs.Text("999","40px "+FONT_GAME,TEXT_COLOR_STROKE);b.textAlign="center";b.textBaseline="middle";b.x=-7;b.outline=3;q.addChild(b);e=new createjs.Text("999","40px "+FONT_GAME,TEXT_COLOR);e.textAlign="center";e.textBaseline="middle";e.x=b.x;q.addChild(e);var l=
s_oSpriteLibrary.getSprite("bg_score"),m=createBitmap(l);m.regX=.5*l.width;m.regY=.5*l.height;q.addChild(m);q.x=-360;f=new createjs.Text("25","40px "+FONT_GAME,TEXT_COLOR_STROKE);f.textAlign="center";f.textBaseline="middle";f.outline=3;f.x=-5;k.addChild(f);g=new createjs.Text("25","40px "+FONT_GAME,TEXT_COLOR);g.textAlign="center";g.textBaseline="middle";g.x=f.x;k.addChild(g);c={x:k.x,y:0};l=this.createStar();k.addChild(l);p=this.createStar();p.visible=!1;p.alpha=0;k.addChild(p)};this.createStar=
function(){var a=s_oSpriteLibrary.getSprite("bg_bestscore");a=new createjs.SpriteSheet({images:[a],frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{normal:[0],active:[1]}});a=createSprite(a,"normal",a.width/2/2,a.height/2,a.width/2,a.height);a.y=-5;a.x=5;return a};this.getStartPosScore=function(){return d};this.getStartPosBestScore=function(){return c};this.setBestScorePos=function(a,b){k.x=a;k.y=b};this.setPosScore=function(a,b){n.x=a;n.y=b};this.refreshTextBestScore=
function(a,b){g.text=a;f.text=a;b&&(p.visible=!0,createjs.Tween.get(p,{override:!0}).to({alpha:1},250,createjs.Ease.cubicOut).to({alpha:0},250,createjs.Ease.cubicIn).set({visible:!1}))};this.refreshTextScore=function(a){e.text=a;b.text=a};this._init();return this}
function CStack(a,d,c,e){var b,g,f,n,q,k,p=0,l,m,u,w,z,B;this._init=function(a,b,c){u=new createjs.Container;e.addChild(u);w=new createjs.Shape;z=new createjs.Shape;B=b;p=a.dir;k=new CVector2(DIRECTION_STACKS[a.dir].x,DIRECTION_STACKS[a.dir].y);q=[];this.setPosition(a.x,a.y);this.setEdges(c,{x:u.x,y:u.y});this.updateSize();u.addChild(w);u.addChild(z)};this.setLimitPosition=function(a){for(var b=0;b<a.length;b++)q.push(a[b])};this.getLimitPosition=function(a){return q[a]};this.getAllLimitPosition=
function(){return q};this.getLeftDownAndRightUpEdges=function(){return g};this.getLeftUpAndRightDownEdges=function(){return f};this.setDir=function(a){k.set(a.x,a.y)};this.getDir=function(){return k};this.isVisible=function(){return u.visible};this.setVisible=function(a){u.visible=a};this.getPosLocal=function(){return e.localToGlobal(u.x,u.y)};this.getDirID=function(){return p};this.getID=function(){return l};this.setID=function(a){l=a};this.cacheStack=function(){};this.updateCache=function(){};this.updateSize=
function(){this.createGraph(b,B);this.createDepthEdge();this.updateDepthEffect(n,B,!0)};this.createDepthEdge=function(){n=[];n.push({x:b[1].getPointA().getX(),y:b[1].getPointA().getY()});n.push({x:b[1].getPointB().getX(),y:b[1].getPointB().getY()});n.push({x:b[2].getPointB().getX(),y:b[2].getPointB().getY()});n.push({x:b[2].getPointB().getX(),y:b[2].getPointB().getY()+STACK_DEPTH_SIZE});n.push({x:b[1].getPointB().getX(),y:b[1].getPointB().getY()+STACK_DEPTH_SIZE});n.push({x:b[1].getPointA().getX(),
y:b[1].getPointA().getY()+STACK_DEPTH_SIZE})};this.updateDepthEffect=function(a,b,c){c&&(B.depth=colorLuminance(B.plane,DEPTH_LUMINANCE));z.graphics.clear();SHOW_EDGES&&z.graphics.beginStroke(b.depth);SHOW_FILL&&z.graphics.beginFill(b.depth);z.graphics.setStrokeStyle(B.width);for(b=0;b<a.length;b++)z.graphics.lineTo(a[b].x,a[b].y);z.graphics.closePath();z.x=-u.x;z.y=-u.y};this.perfectPosition=function(){var a=hexToRgb(B.plane),c=hexToRgb(colorLuminance(B.plane,.5)),d=this;new colorLerpShape(w,{r:a.r,
g:a.g,b:a.b,lerp:0},{r:c.r,g:c.g,b:c.b,lerp:1},0,MS_TIME_PERFECT_HIT,this.createGraph,createjs.Ease.cubicOut,b,"plane",function(){new colorLerpShape(w,{r:c.r,g:c.g,b:c.b,lerp:0},{r:a.r,g:a.g,b:a.b,lerp:1},0,MS_TIME_PERFECT_HIT,d.createGraph,createjs.Ease.cubicOut,b,"plane",null)});var e=hexToRgb(B.depth),f=hexToRgb(colorLuminance(B.depth,.5));new colorLerpShape(z,{r:e.r,g:e.g,b:e.b,lerp:0},{r:f.r,g:f.g,b:f.b,lerp:1},0,MS_TIME_PERFECT_HIT,this.updateDepthEffect,createjs.Ease.cubicOut,n,"depth",function(){new colorLerpShape(z,
{r:f.r,g:f.g,b:f.b,lerp:0},{r:e.r,g:e.g,b:e.b,lerp:1},0,MS_TIME_PERFECT_HIT,d.updateDepthEffect,createjs.Ease.cubicOut,n,"depth",null)})};this.updateEdgesPosition=function(){for(var a=0;a<b.length;a++)b[a].set(u.x+m[a].getPointA().getX(),u.y+m[a].getPointA().getY(),u.x+m[a].getPointB().getX(),u.y+m[a].getPointB().getY())};this.createGraph=function(a,b){w.graphics.clear();SHOW_EDGES&&w.graphics.beginStroke(b.plane);SHOW_FILL&&w.graphics.beginFill(b.plane);w.graphics.setStrokeStyle(B.width);for(var c=
0;c<a.length;c++)w.graphics.lineTo(a[c].getPointA().getX(),a[c].getPointA().getY());w.graphics.closePath();w.x=-u.x;w.y=-u.y};this.setChildIndex=function(a){e.setChildIndex(u,a)};this.getChildIndex=function(){return e.getChildIndex(u)};this.fallEffect=function(){createjs.Tween.get(u).to({y:CANVAS_HEIGHT,alpha:0},1500,createjs.Ease.cubicIn).call(function(){e.removeChild(u)})};this.getColor=function(){return B};this.setPosition=function(a,b){u.x=a;u.y=b};this.getPos=function(){return{x:u.x,y:u.y}};
this.getEdges=function(){return b};this.getLocalEdges=function(){return m};this.setEdges=function(a,c){m=[];b=[];g=[];f=[];for(var d=0;d<NUM_OF_EDGES_FOR_STACK;d++){m[d]=new CEdge(a[d].getPointA().getX(),a[d].getPointA().getY(),a[d].getPointB().getX(),a[d].getPointB().getY(),START_EDGES_POSITION[d].type);var e=new CEdge(a[d].getPointA().getX()+c.x,a[d].getPointA().getY()+c.y,a[d].getPointB().getX()+c.x,a[d].getPointB().getY()+c.y,START_EDGES_POSITION[d].type);START_EDGES_POSITION[d].type===EDGE_RIGHT_UP||
START_EDGES_POSITION[d].type===EDGE_LEFT_DOWN?g.push(e):f.push(e);b.push(e)}};this.edgesToString=function(a){console.log("------------"+a+"-------------");for(a=0;a<NUM_OF_EDGES_FOR_STACK;a++)console.log(b[a].toString())};this.limitLeftDown=function(){(u.x<=q[p].x||u.y>=q[p].y)&&this.resetStack(RIGHT_UP)};this.limitRightDown=function(){(u.x>=q[p].x||u.y>=q[p].y)&&this.resetStack(LEFT_UP)};this.limitLeftUp=function(){(u.x<=q[p].x||u.y<=q[p].y)&&this.resetStack(RIGHT_DOWN)};this.limitRightUp=function(){(u.x>=
q[p].x||u.y<=q[p].y)&&this.resetStack(LEFT_DOWN)};this.unload=function(){e.removeChild(u)};this.resetStack=function(a){p=a;k.set(DIRECTION_STACKS[p].x,DIRECTION_STACKS[p].y)};this.update=function(a){u.x+=k.getX()*a;u.y+=k.getY()*a;switch(p){case LEFT_DOWN:this.limitLeftDown();break;case RIGHT_DOWN:this.limitRightDown();break;case LEFT_UP:this.limitLeftUp();break;case RIGHT_UP:this.limitRightUp()}};this._init(a,d,c);return this}
function CTextPerfect(a){var d,c,e,b,g,f;this._init=function(){f=new createjs.Container;a.addChild(f);g=new CTLText(f,-350,-200,700,100,100,"center",TEXT_COLOR_STROKE,FONT_GAME,1,0,0,TEXT_PERFECT,!0,!0,!1,!1);g.setOutline(3);new CTLText(f,-350,-200,700,100,100,"center",TEXT_COLOR,FONT_GAME,1,0,0,TEXT_PERFECT,!0,!0,!1,!1);e=PERFECT_TEXT_START_POINT.x;b=PERFECT_TEXT_START_POINT.y-s_iOffsetY;d=PERFECT_TEXT_END_POINT.x;c=PERFECT_TEXT_END_POINT.y-s_iOffsetY};this.updatePoints=function(a,d){b=PERFECT_TEXT_START_POINT.y-
d;c=PERFECT_TEXT_END_POINT.y-d};this.animText=function(){f.x=e;f.y=b;f.visible=!0;f.alpha=1;createjs.Tween.get(f,{override:!0}).to({x:d,y:c,alpha:0},MS_PERFECT_TEXT,createjs.Ease.cubicOut).set({visible:!1})};this._init();return this}
CTLText.prototype={constructor:CTLText,__autofit:function(){if(this._bFitText){for(var a=this._iFontSize;(this._oText.getBounds().height>this._iHeight-2*this._iPaddingV||this._oText.getBounds().width>this._iWidth-2*this._iPaddingH)&&!(a--,this._oText.font=a+"px "+this._szFont,this._oText.lineHeight=Math.round(a*this._fLineHeightFactor),this.__updateY(),this.__verticalAlign(),8>a););this._iFontSize=a}},__verticalAlign:function(){if(this._bVerticalAlign){var a=this._oText.getBounds().height;this._oText.y-=
(a-this._iHeight)/2+this._iPaddingV}},__updateY:function(){this._oText.y=this._y+this._iPaddingV;switch(this._oText.textBaseline){case "middle":this._oText.y+=this._oText.lineHeight/2+(this._iFontSize*this._fLineHeightFactor-this._iFontSize)}},__createText:function(a){this._bDebug&&(this._oDebugShape=new createjs.Shape,this._oDebugShape.graphics.beginFill("rgba(255,0,0,0.5)").drawRect(this._x,this._y,this._iWidth,this._iHeight),this._oContainer.addChild(this._oDebugShape));this._oText=new createjs.Text(a,
this._iFontSize+"px "+this._szFont,this._szColor);this._oText.textBaseline="middle";this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this._oText.textAlign=this._szAlign;this._oText.lineWidth=this._bMultiline?this._iWidth-2*this._iPaddingH:null;switch(this._szAlign){case "center":this._oText.x=this._x+this._iWidth/2;break;case "left":this._oText.x=this._x+this._iPaddingH;break;case "right":this._oText.x=this._x+this._iWidth-this._iPaddingH}this._oContainer.addChild(this._oText);
this.refreshText(a)},setVerticalAlign:function(a){this._bVerticalAlign=a},setOutline:function(a){null!==this._oText&&(this._oText.outline=a)},setShadow:function(a,d,c,e){null!==this._oText&&(this._oText.shadow=new createjs.Shadow(a,d,c,e))},setColor:function(a){this._oText.color=a},setAlpha:function(a){this._oText.alpha=a},removeTweens:function(){createjs.Tween.removeTweens(this._oText)},getText:function(){return this._oText},getY:function(){return this._y},getFontSize:function(){return this._iFontSize},
refreshText:function(a){""===a&&(a=" ");null===this._oText&&this.__createText(a);this._oText.text=a;this._oText.font=this._iFontSize+"px "+this._szFont;this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this.__autofit();this.__updateY();this.__verticalAlign()}};
function CTLText(a,d,c,e,b,g,f,n,q,k,p,l,m,u,w,z,B){this._oContainer=a;this._x=d;this._y=c;this._iWidth=e;this._iHeight=b;this._bMultiline=z;this._iFontSize=g;this._szAlign=f;this._szColor=n;this._szFont=q;this._iPaddingH=p;this._iPaddingV=l;this._bVerticalAlign=w;this._bFitText=u;this._bDebug=B;this._oDebugShape=null;this._fLineHeightFactor=k;this._oText=null;m&&this.__createText(m)};